# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ethbot
email: Joker.Qyou@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A telegram bot, include an awesome pushbot feature
baseurl: "/ethbot" # the subpath of your site, e.g. /blog
url: "https://jokerqyou.github.io" # the base hostname & protocol for your site
github_username:  jokerqyou

permalink: :title

# Build settings
markdown: kramdown
